import console from 'console-browserify';
export default console;
export var assert = console.assert;
export var clear = console.clear;
export var context = console.context;
export var count = console.count;
export var countReset = console.countReset;
export var debug = console.debug;
export var dir = console.dir;
export var dirxml = console.dirxml;
export var error = console.error;
export var group = console.group;
export var groupCollapsed = console.groupCollapsed;
export var groupEnd = console.groupEnd;
export var info = console.info;
export var log = console.log;
export var memory = console.memory;
export var profile = console.profile;
export var profileEnd = console.profileEnd;
export var table = console.table;
export var time = console.time;
export var timeEnd = console.timeEnd;
export var timeStamp = console.timeStamp;
export var trace = console.trace;
export var warn = console.warn;
