import * as promises from './fs-promises.js';

function unimplemented () {
  throw new Error('Node.js fs module is not supported by jspm core in the browser'));
}

export default {
  appendFile: unimplemented,
  appendFileSync: unimplemented,
  access: unimplemented,
  accessSync: unimplemented,
  chown: unimplemented,
  chownSync: unimplemented,
  chmod: unimplemented,
  chmodSync: unimplemented,
  close: unimplemented,
  closeSync: unimplemented,
  copyFile: unimplemented,
  copyFileSync: unimplemented,
  createReadStream: unimplemented,
  createWriteStream: unimplemented,
  exists: unimplemented,
  existsSync: unimplemented,
  fchown: unimplemented,
  fchownSync: unimplemented,
  fchmod: unimplemented,
  fchmodSync: unimplemented,
  fdatasync: unimplemented,
  fdatasyncSync: unimplemented,
  fstat: unimplemented,
  fstatSync: unimplemented,
  fsync: unimplemented,
  fsyncSync: unimplemented,
  ftruncate: unimplemented,
  ftruncateSync: unimplemented,
  futimes: unimplemented,
  futimesSync: unimplemented,
  lchown: unimplemented,
  lchownSync: unimplemented,
  lchmod: unimplemented,
  lchmodSync: unimplemented,
  link: unimplemented,
  linkSync: unimplemented,
  lstat: unimplemented,
  lstatSync: unimplemented,
  mkdir: unimplemented,
  mkdirSync: unimplemented,
  mkdtemp: unimplemented,
  mkdtempSync: unimplemented,
  open: unimplemented,
  openSync: unimplemented,
  opendir: unimplemented,
  opendirSync: unimplemented,
  readdir: unimplemented,
  readdirSync: unimplemented,
  read: unimplemented,
  readSync: unimplemented,
  readFile: unimplemented,
  readFileSync: unimplemented,
  readlink: unimplemented,
  readlinkSync: unimplemented,
  realpath: unimplemented,
  realpathSync: unimplemented,
  rename: unimplemented,
  renameSync: unimplemented,
  rmdir: unimplemented,
  rmdirSync: unimplemented,
  stat: unimplemented,
  statSync: unimplemented,
  symlink: unimplemented,
  symlinkSync: unimplemented,
  truncate: unimplemented,
  truncateSync: unimplemented,
  unwatchFile: unimplemented,
  unlink: unimplemented,
  unlinkSync: unimplemented,
  utimes: unimplemented,
  utimesSync: unimplemented,
  watch: unimplemented,
  watchFile: unimplemented,
  writeFile: unimplemented,
  writeFileSync: unimplemented,
  write: unimplemented,
  writeSync: unimplemented,
  writev: unimplemented,
  writevSync: unimplemented,
  Dir: unimplemented,
  Dirent: unimplemented,
  Stats: unimplemented,
  ReadStream: unimplemented,
  WriteStream: unimplemented,
  FileReadStream: unimplemented,
  FileWriteStream: unimplemented,
  _toUnixTimestamp: unimplemented,
  F_OK: null,
  R_OK: null,
  W_OK: null,
  X_OK: null,
  constants: null,
  promises: promises
};

export var F_OK = null,
  R_OK = null,
  W_OK = null,
  X_OK = null,
  constants = null;

export {
  unimplemented as appendFile,
  unimplemented as appendFileSync,
  unimplemented as access,
  unimplemented as accessSync,
  unimplemented as chown,
  unimplemented as chownSync,
  unimplemented as chmod,
  unimplemented as chmodSync,
  unimplemented as close,
  unimplemented as closeSync,
  unimplemented as copyFile,
  unimplemented as copyFileSync,
  unimplemented as createReadStream,
  unimplemented as createWriteStream,
  unimplemented as exists,
  unimplemented as existsSync,
  unimplemented as fchown,
  unimplemented as fchownSync,
  unimplemented as fchmod,
  unimplemented as fchmodSync,
  unimplemented as fdatasync,
  unimplemented as fdatasyncSync,
  unimplemented as fstat,
  unimplemented as fstatSync,
  unimplemented as fsync,
  unimplemented as fsyncSync,
  unimplemented as ftruncate,
  unimplemented as ftruncateSync,
  unimplemented as futimes,
  unimplemented as futimesSync,
  unimplemented as lchown,
  unimplemented as lchownSync,
  unimplemented as lchmod,
  unimplemented as lchmodSync,
  unimplemented as link,
  unimplemented as linkSync,
  unimplemented as lstat,
  unimplemented as lstatSync,
  unimplemented as mkdir,
  unimplemented as mkdirSync,
  unimplemented as mkdtemp,
  unimplemented as mkdtempSync,
  unimplemented as open,
  unimplemented as openSync,
  unimplemented as opendir,
  unimplemented as opendirSync,
  unimplemented as readdir,
  unimplemented as readdirSync,
  unimplemented as read,
  unimplemented as readSync,
  unimplemented as readFile,
  unimplemented as readFileSync,
  unimplemented as readlink,
  unimplemented as readlinkSync,
  unimplemented as realpath,
  unimplemented as realpathSync,
  unimplemented as rename,
  unimplemented as renameSync,
  unimplemented as rmdir,
  unimplemented as rmdirSync,
  unimplemented as stat,
  unimplemented as statSync,
  unimplemented as symlink,
  unimplemented as symlinkSync,
  unimplemented as truncate,
  unimplemented as truncateSync,
  unimplemented as unwatchFile,
  unimplemented as unlink,
  unimplemented as unlinkSync,
  unimplemented as utimes,
  unimplemented as utimesSync,
  unimplemented as watch,
  unimplemented as watchFile,
  unimplemented as writeFile,
  unimplemented as writeFileSync,
  unimplemented as write,
  unimplemented as writeSync,
  unimplemented as writev,
  unimplemented as writevSync,
  unimplemented as Dir,
  unimplemented as Dirent,
  unimplemented as Stats,
  unimplemented as ReadStream,
  unimplemented as WriteStream,
  unimplemented as FileReadStream,
  unimplemented as FileWriteStream,
  unimplemented as _toUnixTimestamp,
  promises
}
