import https from 'https-browserify';
export default https;
export var Agent = https.Agent;
export var ClientRequest = https.ClientRequest;
export var IncomingMessage = https.IncomingMessage;
export var METHODS = https.METHODS;
export var STATUS_CODES = https.STATUS_CODES;
export var get = https.get;
export var globalAgent = https.globalAgent;
export var request = https.request;
