import os from 'os-browserify';
export default os;
export var EOL = os.EOL;
export var arch = os.arch;
export var cpus = os.cpus;
export var endianness = os.endianness;
export var freemem = os.freemem;
export var getNetworkInterfaces = os.getNetworkInterfaces;
export var homedir = os.homedir;
export var hostname = os.hostname;
export var loadavg = os.loadavg;
export var networkInterfaces = os.networkInterfaces;
export var platform = os.platform;
export var release = os.release;
export var tmpDir = os.tmpDir;
export var tmpdir = os.tmpdir;
export var totalmem = os.totalmem;
export var type = os.type;
export var uptime = os.uptime;