import path from 'path-browserify';
export default path;
export var _makeLong = path._makeLong;
export var basename = path.basename;
export var delimiter = path.delimiter;
export var dirname = path.dirname;
export var extname = path.extname;
export var format = path.format;
export var isAbsolute = path.isAbsolute;
export var join = path.join;
export var normalize = path.normalize;
export var parse = path.parse;
export var posix = path.posix;
export var relative = path.relative;
export var resolve = path.resolve;
export var sep = path.sep;
export var win32 = path.win32;
