import assert from 'browserify-assert';
export default assert;
export var AssertionError = assert.AssertionError;
export var deepEqual = assert.deepEqual;
export var deepStrictEqual = assert.deepStrictEqual;
export var doesNotReject = assert.doesNotReject;
export var doesNotThrow = assert.doesNotThrow;
export var equal = assert.equal;
export var fail = assert.fail;
export var ifError = assert.ifError;
export var notDeepEqual = assert.notDeepEqual;
export var notDeepStrictEqual = assert.notDeepStrictEqual;
export var notEqual = assert.notEqual;
export var notStrictEqual = assert.notStrictEqual;
export var ok = assert.ok;
export var rejects = assert.rejects;
export var strict = assert.strict;
export var strictEqual = assert.strictEqual;
export var throws = assert.throws;
