import stream from 'browserify-stream';
export default stream;
export var Readable = stream.Readable;
export var Writable = stream.Writable;
export var Duplex = stream.Duplex;
export var Transform = stream.Transform;
export var PassThrough = stream.PassThrough;
export var finished = stream.finished;
export var pipeline = stream.pipeline;
export var Stream = stream.Stream;
